In [3]:
import numpy as np
import sys
sys.path.append("..")
from reference.lib.envs.gridworld import GridworldEnv

In [4]:
env = GridworldEnv()

In [11]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    
    # loop until convergence - system is stable
    while True:
        # this is the change value
        delta_value = 0
        
        # for every state value
        for i in range(len(V)):
            
            current_state = V[i]
            
            for policy_index in range(4):
                action = policy_index
                action_prob = policy[i,policy_index]
                
                for prob, next_state, reward, done in env.P[i][action]:
                    current_state = current_state + action_prob * prob * (reward + discount_factor * V[next_state]) 
                    
            delta_value = max(delta_value,np.abs(current_state-V[i]))
            V[i] = current_state
            
        if delta_value < theta: 
            break
            
    return np.array(V)

In [15]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)
print(v.reshape((4,4)))

[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]


In [10]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
print(
    np.testing.assert_array_almost_equal(v, expected_v, decimal=2)
)

None


In [36]:
! start .