In [42]:
import numpy as np
import sys
sys.path.append("..")
from reference.lib.envs.gridworld import GridworldEnv

In [44]:
env = GridworldEnv()

In [86]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    
    # loop until convergence - system is stable
    while True:
        # this is the change value
        delta_value = 0
        
        # for every state value
        for i in range(len(V)):
            current_state = V[i]
            
            for policy_index in range(4):
                action = policy_index
                action_prob = policy[i,policy_index]
                
                for prob, next_state, reward, done in env.P[i][action]:
                    current_state = current_state + action_prob * prob * (reward + discount_factor * V[next_state]) 
                    
            delta_value = max(delta_value,np.abs(current_state-V[i]))
            V[i] = current_state
            
        if delta_value<theta: break
        print(V.reshape((4,4)))
        input()
        
    return np.array(V)

In [87]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

print(v.reshape((4,4)))

[[ 0.        -1.        -1.25      -1.3125   ]
 [-1.        -1.5       -1.6875    -1.75     ]
 [-1.25      -1.6875    -1.84375   -1.8984375]
 [-1.3125    -1.75      -1.8984375  0.       ]]

[[ 0.         -2.9375     -4.046875   -4.41796875]
 [-2.9375     -4.8125     -5.80078125 -6.21679688]
 [-4.046875   -5.80078125 -6.69335938 -6.60058594]
 [-4.41796875 -6.21679688 -6.60058594  0.        ]]

[[  0.          -6.88671875 -10.33496094 -11.76489258]
 [ -6.88671875 -12.15625    -15.65112305 -17.27514648]
 [-10.33496094 -15.65112305 -18.81921387 -18.27432251]
 [-11.76489258 -17.27514648 -18.27432251   0.        ]]

[[  0.         -15.23120117 -24.58050537 -29.11125183]
 [-15.23120117 -28.59741211 -38.9691925  -44.18262482]
 [-24.58050537 -38.9691925  -48.44097137 -46.99880219]
 [-29.11125183 -44.18262482 -46.99880219   0.        ]]

[[   0.          -33.33348083  -57.07911301  -69.9823122 ]
 [ -33.33348083  -65.74874878  -93.832057   -108.93157387]
 [ -57.07911301  -93.832057   -119.8564009

KeyboardInterrupt: 

In [22]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 87.5%)
 x: array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])
 y: array([  0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22,
       -20, -14,   0])

In [36]:
! start .