In [28]:
# import lib
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.datasets import make_moons,make_classification,make_regression,make_circles
import sys
from mpl_toolkits.mplot3d import Axes3D 
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.decomposition import PCA,KernelPCA
np.random.seed(23)
np.set_printoptions(precision=3,suppress=True)
plt.style.use('seaborn')

import os
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
tf.logging.set_verbosity(tf.logging.ERROR)
from tensorflow.examples.tutorials.mnist import input_data

def _sym_decorrelation(W):
    """ Symmetric decorrelation
    i.e. W <- (W * W.T) ^{-1/2} * W
    """
    s, u = np.linalg.eigh(np.dot(W, W.T))
    # u (resp. s) contains the eigenvectors (resp. square roots of
    # the eigenvalues) of W * W.T
    return np.dot(np.dot(u * (1./(np.sqrt(s+1e-8))+1e-8), u.T), W)

In [29]:
# import data
mnist = input_data.read_data_sets('../../Dataset/MNIST/', one_hot=True)
train_data,train_label,val_data,val_label,test_data,test_label = mnist.train.images,mnist.train.labels,mnist.validation.images,mnist.validation.labels,mnist.test.images, mnist.test.labels
print(train_data.shape,train_label.shape,train_data.max(),train_data.min())
print(val_data.shape,val_label.shape,val_data.max(),val_data.min())
print(test_data.shape,test_label.shape,test_data.max(),test_data.min())

Extracting ../../Dataset/MNIST/train-images-idx3-ubyte.gz
Extracting ../../Dataset/MNIST/train-labels-idx1-ubyte.gz
Extracting ../../Dataset/MNIST/t10k-images-idx3-ubyte.gz
Extracting ../../Dataset/MNIST/t10k-labels-idx1-ubyte.gz
(55000, 784) (55000, 10) 1.0 0.0
(5000, 784) (5000, 10) 1.0 0.0
(10000, 784) (10000, 10) 1.0 0.0


In [38]:
# start session 
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning:

An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).



In [31]:
#  create class
def arctan(x):  return tf.arctan(x)
def tan(x)   :  return tf.tan(x)
def d_arctan(x):return 1/(1+x**2)
def d_tanh(x):  return 1/tf.cos(x)

class FNN():
    
    def __init__(self,input,output,act,d_act):
        self.w = tf.Variable(tf.random.normal())
        self.mw,self.mv = np.zeros_like()
        
        self.a = np.ones(output)
        self.b = np.ones(output)
        self.c = np.zeros(output)
        
        self.act  = act
        self.d_act= d_act

In [196]:
def tf_arctan(x): return tf.atan(x)
def tf_tan(x)   : return tf.tan(x)

def d_tf_arctan(x): return 1/(1+x**2)
def d_tf_tan(x):    return 1/(tf.cos(x)**2)

class PCA_Layer():

    def __init__(self,inc,outc,act=tf_arctan,d_act=d_tf_arctan):
        
        if outc == 1:
            self.w = tf.Variable(self.norm(tf.random_normal([inc,outc],stddev=1,seed=2)))
        else:
            self.w = tf.Variable(tf.random_normal([inc,outc],stddev=0.05,seed=2))
        self.a = tf.Variable(tf.ones([outc]))
        self.b = tf.Variable(tf.ones([outc]))
        self.c = tf.Variable(tf.zeros([outc]))
        
        self.mw,self.vw = tf.Variable(tf.zeros_like(self.w)),tf.Variable(tf.zeros_like(self.w))
        self.ma,self.va = tf.Variable(tf.zeros_like(self.a)),tf.Variable(tf.zeros_like(self.a))
        self.mb,self.vb = tf.Variable(tf.zeros_like(self.b)),tf.Variable(tf.zeros_like(self.b))
        self.mc,self.vc = tf.Variable(tf.zeros_like(self.c)),tf.Variable(tf.zeros_like(self.c))
        
        self.act,self.d_act = act,d_act

    def feedforward(self,input=None):
        self.input  = input
        self.layer  = tf.matmul(self.input,self.w) 
        self.layerA = self.a*self.act(self.b*self.layer) + self.c
        return self.layerA
    
    def backprop_first(self):
        pass 

    def backprop(self,gradient=None,which_reg=0):
        grad_part_1 = gradient
        grad_part_2 = self.d_act(self.layer)
        grad_part_3 = self.input

        grad_middle = grad_part_1 * grad_part_2
        grad  = tf.matmul(tf.transpose(grad_part_3),grad_middle)/batch_size
        grad_b= tf.reduce_mean(grad_middle,axis=0)
        grad_pass = tf.matmul(grad_middle,tf.transpose(self.w))

        update_w = []

        # Update the Weight First
        update_w.append(tf.assign( self.m,self.m*beta1 + (1-beta1) * (grad)   ))
        update_w.append(tf.assign( self.v,self.v*beta2 + (1-beta2) * (grad ** 2)   ))
        m_hat = self.m / (1-beta1)
        v_hat = self.v / (1-beta2)
        adam_middle = m_hat *  learning_rate/(tf.sqrt(v_hat) + adam_e)
        update_w.append(tf.assign(self.w,tf.subtract(self.w,adam_middle )))

        return grad_pass,update_w
    
    def norm(self,W):
        W = W/(tf.sqrt(tf.reduce_sum(W**2)+1e-8))
        return W
    
    def sym_decorrelation(self,W):
        s, u = tf.linalg.eigh(W@tf.transpose(W))
        #        (u * (1./(np.sqrt(s+1e-8)+1e-8))) @ u.T @ W
        result = (u * (1./(tf.sqrt(s+1e-5)+1e-5))) @ tf.transpose(u) @ W
        return result


In [197]:
temp = np.ones((10,784)).astype(np.float32)
               
layer1 = PCA_Layer(784,256)
sess.run(tf.global_variables_initializer())
te = layer1.w.eval()


In [198]:
te.T @ te

array([[ 2.08 , -0.023,  0.021, ...,  0.061,  0.004, -0.112],
       [-0.023,  2.031,  0.019, ...,  0.099, -0.024, -0.088],
       [ 0.021,  0.019,  1.912, ...,  0.026, -0.016, -0.097],
       ...,
       [ 0.061,  0.099,  0.026, ...,  1.896, -0.026,  0.059],
       [ 0.004, -0.024, -0.016, ..., -0.026,  1.917,  0.012],
       [-0.112, -0.088, -0.097, ...,  0.059,  0.012,  1.843]],
      dtype=float32)

In [199]:
te

array([[-0.043, -0.01 ,  0.007, ...,  0.031, -0.004, -0.03 ],
       [ 0.057,  0.002, -0.011, ...,  0.097, -0.01 ,  0.009],
       [ 0.037,  0.054,  0.052, ...,  0.063, -0.045,  0.075],
       ...,
       [-0.056,  0.027,  0.04 , ...,  0.026,  0.043, -0.049],
       [-0.07 , -0.003, -0.052, ..., -0.048,  0.01 , -0.075],
       [ 0.032,  0.104,  0.084, ...,  0.024, -0.014, -0.087]],
      dtype=float32)

In [201]:
ss  =np.random.randn(784,256)
def _sym_decorrelation(W):
    """ Symmetric decorrelation
    i.e. W <- (W * W.T) ^{-1/2} * W
    """
    s, u = np.linalg.eigh(np.dot(W, W.T))
    # u (resp. s) contains the eigenvectors (resp. square roots of
    # the eigenvalues) of W * W.T
    return (u * (1./(np.sqrt(s+1e-5)+1e-5))) @ u.T @ W

sss = _sym_decorrelation(te)
sssss = layer1.sym_decorrelation(te).eval()
print(sss.T@sss)
print(sssss.T@sssss)

[[ 1.  0. -0. ... -0.  0. -0.]
 [ 0.  1.  0. ... -0.  0. -0.]
 [-0.  0.  1. ... -0.  0.  0.]
 ...
 [-0. -0. -0. ...  1.  0. -0.]
 [ 0.  0.  0. ...  0.  1. -0.]
 [-0. -0.  0. ... -0. -0.  1.]]
[[ 1.  0. -0. ...  0. -0.  0.]
 [ 0.  1.  0. ... -0. -0. -0.]
 [-0.  0.  1. ...  0. -0. -0.]
 ...
 [ 0. -0.  0. ...  1.  0.  0.]
 [-0. -0. -0. ...  0.  1. -0.]
 [ 0. -0. -0. ...  0. -0.  1.]]


In [184]:
ss

array([[-0.577, -0.312, -0.443, ..., -1.426, -0.966, -1.478],
       [-0.427, -0.168,  2.35 , ..., -2.   , -1.397, -0.426],
       [-0.747, -1.449, -0.905, ...,  0.102, -0.432,  0.307],
       ...,
       [ 0.874,  3.734,  0.054, ...,  0.445,  1.5  ,  0.948],
       [ 0.42 , -1.197, -0.118, ..., -0.129, -1.749,  1.076],
       [ 1.201, -1.433, -1.776, ..., -0.293,  1.725, -0.487]])