In [1]:
# import lib
import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt 
import sys, os,cv2
from sklearn.utils import shuffle
from scipy.misc import imread,imresize
from keras.utils import to_categorical
plt.style.use('seaborn-white'); os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
np.random.seed(678); tf.set_random_seed(678)

Using TensorFlow backend.


In [2]:
# prepare STL 10
def read_all_images(path_to_data):
    """
    :param path_to_data: the file containing the binary images from the STL-10 dataset
    :return: an array containing all the images
    """

    with open(path_to_data, 'rb') as f:
        # read whole file in uint8 chunks
        everything = np.fromfile(f, dtype=np.uint8)

        # We force the data into 3x96x96 chunks, since the
        # images are stored in "column-major order", meaning
        # that "the first 96*96 values are the red channel,
        # the next 96*96 are green, and the last are blue."
        # The -1 is since the size of the pictures depends
        # on the input file, and this way numpy determines
        # the size on its own.

        images = np.reshape(everything, (-1, 3, 96, 96))

        # Now transpose the images into a standard image format
        # readable by, for example, matplotlib.imshow
        # You might want to comment this line or reverse the shuffle
        # if you will use a learning algorithm like CNN, since they like
        # their channels separated.
        images = np.transpose(images, (0, 3, 2, 1))
        return images
def read_labels(path_to_labels):
    """
    :param path_to_labels: path to the binary file containing labels from the STL-10 dataset
    :return: an array containing the labels
    """
    with open(path_to_labels, 'rb') as f:
        labels = np.fromfile(f, dtype=np.uint8)
        
        return labels

In [151]:
# load the data
x_train,y_train = read_all_images('../Dataset/STL10/stl10_binary/train_x.bin'),read_labels('../Dataset/STL10/stl10_binary/train_y.bin')
x_test,y_test   = read_all_images('../Dataset/STL10/stl10_binary/test_x.bin'),read_labels('../Dataset/STL10/stl10_binary/test_y.bin')

y_train = to_categorical(y_train-1)
y_test  = to_categorical(y_test-1)

x_train = (x_train-x_train.min((1,2),keepdims=True))/(x_train.max((1,2),keepdims=True)-x_train.min((1,2),keepdims=True))
x_train = (x_train-x_train.mean((1,2),keepdims=True))/(x_train.std((1,2),keepdims=True))
x_test = (x_test-x_test.min((1,2),keepdims=True))/(x_test.max((1,2),keepdims=True)-x_test.min((1,2),keepdims=True))
x_test = (x_test-x_test.mean((1,2),keepdims=True))/(x_test.std((1,2),keepdims=True))

print(x_train.shape,y_train.shape,x_train.min(),x_train.max())
print(x_test.shape,y_test.shape,x_test.min(),x_test.max())

(5000, 96, 96, 3) (5000, 10) -11.595098265964817 15.777090090299724
(8000, 96, 96, 3) (8000, 10) -10.553357891447178 22.92614277238906


In [153]:
# declare hyper parameter
learning_rate = 0.0008 ; beta1 = 0.9; beta2 = 0.999; adam_e = 1e-8
num_epoch     = 30    ; batch_size = 50 ; print_size = 1; 
channel_sizes = 96 

In [164]:
# activation functions
def tf_elu(x):     return tf.nn.elu(x)
def d_tf_elu(x):   return tf.cast(tf.greater(x,0),tf.float32) +  tf.exp(tf.cast(tf.less_equal(x,0),tf.float32) * x)
def tf_iden(x):    return x
def d_tf_iden(x):  return tf.ones_like(x)
def tf_softmax(x): return tf.nn.softmax(x)

class CNN():
    
    def __init__(self,k,inc,out,act=tf_elu,d_act=d_tf_elu):
        self.padding    = 'SAME'
        self.stride     = 1
        self.w          = tf.Variable(tf.random_normal([k,k,inc,out],stddev=0.05))
        self.m,self.v   = tf.Variable(tf.zeros_like(self.w)),tf.Variable(tf.zeros_like(self.w))
        self.act,self.d_act = act,d_act
        
    def getw(self): return self.w
    
    def feedforward(self,input,stride=1,padding='SAME'):
        self.padding= padding; self.stride = stride
        self.input  = input
        self.layer  = tf.nn.conv2d(input,self.w,strides=[1,self.stride,self.stride,1],padding=self.padding) 
        self.layerA = self.act(self.layer)
        return self.layerA
    
    def backprop(self,gradient,iter_num):
        grad_part_1 = gradient 
        grad_part_2 = self.d_act(self.layer) 
        grad_part_3 = self.input

        grad_middle = grad_part_1 * grad_part_2

        grad     = tf.nn.conv2d_backprop_filter(input = grad_part_3,filter_sizes = self.w.shape,out_backprop = grad_middle,
            strides=[1,self.stride,self.stride,1],padding=self.padding
        )/batch_size

        grad_pass = tf.nn.conv2d_backprop_input(input_sizes = self.input.shape,filter= self.w,  out_backprop = grad_middle,
            strides=[1,self.stride,self.stride,1],padding=self.padding
        )

        dimension_shape = (2,3)
        grad_pos      = tf.where(grad>0,tf.ones_like(grad),tf.zeros_like(grad))
        grad_pos_mean = tf.reduce_sum(grad_pos*grad,dimension_shape,keepdims=True)/tf.reduce_sum(grad_pos,dimension_shape,keepdims=True)
        
        grad_neg      = tf.where(grad<0,tf.ones_like(grad),tf.zeros_like(grad))
        grad_neg_mean = tf.reduce_sum(grad_neg*grad,dimension_shape,keepdims=True)/tf.reduce_sum(grad_neg,dimension_shape,keepdims=True)
        
        grad_between    = tf.where(grad_neg_mean<grad,tf.ones_like(grad),tf.zeros_like(grad)) * tf.where(grad_pos_mean>grad,tf.ones_like(grad),tf.zeros_like(grad))
        grad_sign_chage = grad_between     * grad *  -1
        grad_sign_keep  = (1-grad_between) * grad *  1
        
        grad_new = grad_sign_chage + grad_sign_keep
        
        update_w = []
        update_w.append(tf.assign( self.m,self.m*beta1 + (1-beta1) * (grad_new)   ))
        update_w.append(tf.assign( self.v,self.v*beta2 + (1-beta2) * (grad_new ** 2)   ))
        m_hat = self.m / (1-tf.pow(beta1,iter_num))
        v_hat = self.v / (1-tf.pow(beta2,iter_num))
        update_w.append(tf.assign( self.w,self.w - learning_rate*( m_hat/(tf.sqrt(v_hat) + adam_e)   )))
        return grad_pass,update_w  
class tf_batch_norm_layer():
    
    def __init__(self,vector_shape,axis=None):
        self.moving_mean = tf.Variable(tf.zeros(shape=[1,1,1,vector_shape],dtype=tf.float32))
        self.moving_vari = tf.Variable(tf.zeros(shape=[1,1,1,vector_shape],dtype=tf.float32))
        self.axis        = (0,1,2)
        
    def feedforward(self,input,training_phase,eps = 1e-8):
        self.input = input
        self.input_size          = self.input.shape
        self.batch,self.h,self.w,self.c = self.input_size[0].value,self.input_size[1].value,self.input_size[2].value,self.input_size[3].value

        # Training Moving Average Mean         
        def training_fn():
            self.mean    = tf.reduce_mean(self.input,axis=self.axis ,keepdims=True)
            self.var     = tf.reduce_mean(tf.square(self.input-self.mean),axis=self.axis,keepdims=True)
            centered_data= (self.input - self.mean)/tf.sqrt(self.var + eps)
            
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean*0.9 + 0.1 * self.mean ))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari*0.9 + 0.1 * self.var  ))
            return centered_data,update_variable
        
        # Testing Moving Average Mean        
        def  testing_fn():
            centered_data   = (self.input - self.moving_mean)/tf.sqrt(self.moving_vari + eps)
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari))
            return centered_data,update_variable
        
        self.output,update_variable = tf.cond(training_phase,true_fn=training_fn,false_fn=testing_fn)
        return self.output,update_variable
    
    def backprop(self,grad,eps = 1e-8):
        change_parts = 1.0 /(self.batch * self.h * self.w)
        grad_sigma   = tf.reduce_sum( grad *  (self.input-self.mean)     ,axis=self.axis,keepdims=True) * -0.5 * (self.var+eps) ** -1.5
        grad_mean    = tf.reduce_sum( grad *  (-1./tf.sqrt(self.var+eps)),axis=self.axis,keepdims=True) + grad_sigma * change_parts * 2.0 * tf.reduce_sum((self.input-self.mean),axis=self.axis,keepdims=True) * -1
        grad_x       = grad * 1/(tf.sqrt(self.var+eps)) + grad_sigma * change_parts * 2.0 * (self.input-self.mean) + grad_mean * change_parts
        return grad_x
class tf_layer_norm_layer():
    
    def __init__(self,vector_shape):
        self.moving_mean = tf.Variable(tf.zeros(shape=[vector_shape,1,1,1],dtype=tf.float32))
        self.moving_vari = tf.Variable(tf.zeros(shape=[vector_shape,1,1,1],dtype=tf.float32))
        self.axis        = (1,2,3)
        
    def feedforward(self,input,training_phase=True,eps = 1e-8):
        self.input = input
        self.input_size          = self.input.shape
        self.batch,self.h,self.w,self.c = self.input_size[0].value,self.input_size[1].value,self.input_size[2].value,self.input_size[3].value

        # Training Moving Average Mean         
        def training_fn():
            self.mean    = tf.reduce_mean(self.input,axis=self.axis ,keepdims=True)
            self.var     = tf.reduce_mean(tf.square(self.input-self.mean),axis=self.axis,keepdims=True)
            centered_data= (self.input - self.mean)/tf.sqrt(self.var + eps)
            
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean*0.9 + 0.1 * self.mean ))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari*0.9 + 0.1 * self.var  ))
            return centered_data,update_variable
        
        # Testing Moving Average Mean        
        def  testing_fn():
            centered_data   = (self.input - self.moving_mean)/tf.sqrt(self.moving_vari + eps)
            update_variable = []
            update_variable.append(tf.assign(self.moving_mean,self.moving_mean))
            update_variable.append(tf.assign(self.moving_vari,self.moving_vari))
            return centered_data,update_variable
        
        self.output,update_variable = tf.cond(training_phase,true_fn=training_fn,false_fn=testing_fn)
        return self.output,update_variable
    
    def backprop(self,grad,eps = 1e-8):
        change_parts = 1.0 /(self.h * self.w * self.c)
        grad_sigma   = tf.reduce_sum( grad *  (self.input-self.mean)     ,axis=self.axis,keepdims=True) * -0.5 * (self.var+eps) ** -1.5
        grad_mean    = tf.reduce_sum( grad *  (-1./tf.sqrt(self.var+eps)),axis=self.axis,keepdims=True) + grad_sigma * change_parts * 2.0 * tf.reduce_sum((self.input-self.mean),axis=self.axis,keepdims=True) * -1
        grad_x       = grad * 1/(tf.sqrt(self.var+eps)) + grad_sigma * change_parts * 2.0 * (self.input-self.mean) + grad_mean * change_parts
        return grad_x

In [165]:
# declare layer
avg_acc_train = 0; avg_acc_test  = 0; train_acc = [];test_acc = []
avg_lss_train = 0; avg_lss_test  = 0; train_lss = [];test_lss = []

l1   = CNN(3,3,channel_sizes)
l2   = CNN(3,channel_sizes,channel_sizes)
l3   = CNN(3,channel_sizes,channel_sizes)

l4   = CNN(3,channel_sizes,channel_sizes)
l5   = CNN(3,channel_sizes,channel_sizes)
l6   = CNN(3,channel_sizes,channel_sizes)

l7   = CNN(3,channel_sizes,channel_sizes)
l8   = CNN(1,channel_sizes,channel_sizes)
l9   = CNN(1,channel_sizes,10)

In [166]:
# graph
x = tf.placeholder(shape=[batch_size,96,96,3],dtype=tf.float32)
y = tf.placeholder(shape=[batch_size,10],     dtype=tf.float32)
is_train = tf.placeholder_with_default(True,())
iter_num = tf.placeholder_with_default(1.0,())

layer1  = l1. feedforward(x,padding='VALID',stride=2)    
layer2  = l2.feedforward(layer1,padding='VALID') 
layer3  = l3.feedforward(layer2,padding='VALID',stride=2); 

layer4  = l4.feedforward(layer3,padding='VALID');      
layer5  = l5.feedforward(layer4,padding='VALID');      
layer6  = l6.feedforward(layer5,padding='VALID',stride=2)

layer7  = l7.feedforward(layer6,padding='VALID')
layer8  = l8.feedforward(layer7)
layer9  = l9.feedforward(layer8)

final_global = tf.reduce_mean(layer9,[1,2])
final_soft   = tf_softmax(final_global) ; 
cost         = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=final_global,labels=y))
accuracy     = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(final_soft, 1), tf.argmax(y, 1)),tf.float32) )

gradient     = tf.tile((final_soft-y)[:,None,None,:],(1,6,6,1))

grad9, grad9_up  = l9. backprop(gradient,iter_num)
grad8, grad8_up  = l8. backprop(grad9,iter_num)
grad7, grad7_up  = l7. backprop(grad8,iter_num)

grad6, grad6_up  = l6. backprop(grad7,iter_num)
grad5, grad5_up  = l5. backprop(grad6,iter_num)
grad4, grad4_up  = l4. backprop(grad5,iter_num)

grad3,grad3_up   = l3. backprop(grad4,iter_num)
grad2,grad2_up   = l2. backprop(grad3,iter_num)
grad1,grad1_up   = l1. backprop(grad2,iter_num)

grad_update =  grad9_up + grad8_up + grad7_up +\
               grad6_up + grad5_up + grad4_up +\
               grad3_up + grad2_up + grad1_up 

In [167]:
# start the session
# sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))
sess.run(tf.global_variables_initializer())

In [ ]:
# start the training 
for iter in range(1,num_epoch+1):
    for current_batch_index in range(0,len(x_train),batch_size):
        current_data  = x_train[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        current_label = y_train[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        sess_results  = sess.run([accuracy,cost,grad_update],feed_dict={x:current_data,y:current_label,iter_num:iter})
        sys.stdout.write('Current Iter : '+str(iter)+'/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(x_train)) + ' acc : '+str(sess_results[0]) + ' cost : '+str(sess_results[1])+ '\r')
        sys.stdout.flush(); 
        avg_acc_train = avg_acc_train + sess_results[0]
        avg_lss_train = avg_lss_train + sess_results[1]
    for current_batch_index in range(0,len(x_test), batch_size):
        current_data  = x_test[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        current_label = y_test[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        sess_results  = sess.run([accuracy,cost],feed_dict={x:current_data,y:current_label,is_train:False})
        sys.stdout.write('Current Iter : '+str(iter)+'/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(x_test)) + ' acc : '+str(sess_results[0]) + ' cost : '+str(sess_results[1])+ '\r')
        sys.stdout.flush(); 
        avg_acc_test = avg_acc_test + sess_results[0]
        avg_lss_test = avg_lss_test + sess_results[1]
    # ======================== print reset ========================  
    print("Current: "+ str(iter) + 
          "\tTrain Acc: "  + str(avg_acc_train/(len(x_train)/batch_size)) + 
          "\tTrain Cost: " + str(avg_lss_train/(len(x_train)/batch_size)) + 
          "\tTest Acc: "   + str(avg_acc_test/(len(x_test)/batch_size)) + 
          "\tTest Cost: "  + str(avg_lss_test/(len(x_test)/batch_size)) + 
          "\tLR: " + str(learning_rate) )
    avg_acc_train   = 0 ; avg_acc_test  = 0 ; avg_lss_train = 0 ; avg_lss_test  = 0
    x_train,y_train = shuffle(x_train,y_train); x_test,y_test   = shuffle(x_test,y_test)

Current: 1	Train Acc: 0.1677999998629093	Train Cost: 2.219789899587631	Test Acc: 0.23012500004842878	Test Cost: 2.0844263628125193	LR: 0.0008
Current: 2	Train Acc: 0.24259999997913836	Train Cost: 2.031204309463501	Test Acc: 0.27949999962002037	Test Cost: 1.9632594838738442	LR: 0.0008
Current: 3	Train Acc: 0.30980000019073484	Train Cost: 1.8853226137161254	Test Acc: 0.31587500059977175	Test Cost: 1.8337770603597163	LR: 0.0008
Current: 4	Train Acc: 0.3504000014066696	Train Cost: 1.7641406345367432	Test Acc: 0.3666250010952353	Test Cost: 1.7426438741385937	LR: 0.0008


# Global Mean - in weight tensor

In [133]:
# start the training 
for iter in range(1,num_epoch+1):
    for current_batch_index in range(0,len(x_train),batch_size):
        current_data  = x_train[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        current_label = y_train[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        sess_results  = sess.run([accuracy,cost,grad_update],feed_dict={x:current_data,y:current_label,iter_num:iter})
        sys.stdout.write('Current Iter : '+str(iter)+'/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(x_train)) + ' acc : '+str(sess_results[0]) + ' cost : '+str(sess_results[1])+ '\r')
        sys.stdout.flush(); 
        avg_acc_train = avg_acc_train + sess_results[0]
        avg_lss_train = avg_lss_train + sess_results[1]
    for current_batch_index in range(0,len(x_test), batch_size):
        current_data  = x_test[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        current_label = y_test[current_batch_index:current_batch_index+batch_size].astype(np.float32)
        sess_results  = sess.run([accuracy,cost],feed_dict={x:current_data,y:current_label,is_train:False})
        sys.stdout.write('Current Iter : '+str(iter)+'/'+ str(num_epoch)  + ' batch : ' + str(current_batch_index) + '/'+ str(len(x_test)) + ' acc : '+str(sess_results[0]) + ' cost : '+str(sess_results[1])+ '\r')
        sys.stdout.flush(); 
        avg_acc_test = avg_acc_test + sess_results[0]
        avg_lss_test = avg_lss_test + sess_results[1]
    # ======================== print reset ========================  
    print("Current: "+ str(iter) + 
          "\tTrain Acc: "  + str(avg_acc_train/(len(x_train)/batch_size)) + 
          "\tTrain Cost: " + str(avg_lss_train/(len(x_train)/batch_size)) + 
          "\tTest Acc: "   + str(avg_acc_test/(len(x_test)/batch_size)) + 
          "\tTest Cost: "  + str(avg_lss_test/(len(x_test)/batch_size)) + 
          "\tLR: " + str(learning_rate) )
    avg_acc_train   = 0 ; avg_acc_test  = 0 ; avg_lss_train = 0 ; avg_lss_test  = 0
    x_train,y_train = shuffle(x_train,y_train); x_test,y_test   = shuffle(x_test,y_test)

Current: 1	Train Acc: 0.19559999957680702	Train Cost: 2.1409799218177796	Test Acc: 0.27762499884702263	Test Cost: 1.9061641797423363	LR: 0.0008
Current: 2	Train Acc: 0.33500000163912774	Train Cost: 1.78861971616745	Test Acc: 0.3726250001229346	Test Cost: 1.6817388981580734	LR: 0.0008
Current: 3	Train Acc: 0.3965999999642372	Train Cost: 1.6291186547279357	Test Acc: 0.4117499995045364	Test Cost: 1.5833801381289958	LR: 0.0008
Current: 4	Train Acc: 0.4347999981045723	Train Cost: 1.5213914012908936	Test Acc: 0.4377499992959201	Test Cost: 1.51798485070467	LR: 0.0008
Current: 5	Train Acc: 0.4780000001192093	Train Cost: 1.4308626174926757	Test Acc: 0.4556249985471368	Test Cost: 1.4759912744164467	LR: 0.0008
Current: 6	Train Acc: 0.511599999666214	Train Cost: 1.3530434685945512	Test Acc: 0.47649999912828206	Test Cost: 1.4081824906170368	LR: 0.0008
Current: 7	Train Acc: 0.5293999999761582	Train Cost: 1.2989896112680435	Test Acc: 0.48274999875575303	Test Cost: 1.4063894897699356	LR: 0.0008
Curren

KeyboardInterrupt: 

In [149]:
# see 
temp = tf.random_normal([2,5],stddev=1,seed=4)

dimension_shape = (1)
temp_pos      = tf.where(temp>0,tf.ones_like(temp),tf.zeros_like(temp))
temp_pos_mean = tf.reduce_sum(temp_pos*temp,dimension_shape,keepdims=True)/tf.reduce_sum(temp_pos,dimension_shape,keepdims=True)

print(
tf.reduce_sum(temp_pos*temp,1,keepdims=True).shape
)

temp_neg      = tf.where(temp<0,tf.ones_like(temp),tf.zeros_like(temp))
temp_neg_mean = tf.reduce_sum(temp_neg*temp,dimension_shape,keepdims=True)/tf.reduce_sum(temp_neg,dimension_shape,keepdims=True)

temp_between  = tf.where(temp_neg_mean<temp,tf.ones_like(temp),tf.zeros_like(temp)) * tf.where(temp_pos_mean>temp,tf.ones_like(temp),tf.zeros_like(temp)) 

temp1 = temp_between * temp
temp2 = (1-temp_between) * temp

all_of_data = sess.run([temp,temp_between,temp1,temp2])

print(all_of_data[0])
print()
print(all_of_data[1])
print()
print(all_of_data[2])
print()
print(all_of_data[3])






(2, 1)
[[-0.9791961   1.3355689  -0.5717732   1.6240884   0.5671745 ]
 [ 0.3059743   0.3729131  -0.03954097 -0.54076743  0.5313867 ]]

[[0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0.]]

[[-0.          0.         -0.5717732   0.          0.5671745 ]
 [ 0.3059743   0.3729131  -0.03954097 -0.          0.        ]]

[[-0.9791961   1.3355689  -0.          1.6240884   0.        ]
 [ 0.          0.         -0.         -0.54076743  0.5313867 ]]


# Sign Change

In [102]:
# see 
temp = tf.random_normal([5],stddev=1,seed=4)

temp_pos      = tf.where(temp>0,tf.ones_like(temp),tf.zeros_like(temp))
temp_pos_mean = tf.reduce_sum(temp_pos*temp)/tf.reduce_sum(temp_pos)

temp_neg      = tf.where(temp<0,tf.ones_like(temp),tf.zeros_like(temp))
temp_neg_mean = tf.reduce_sum(temp_neg*temp)/tf.reduce_sum(temp_neg)

temp_between  = tf.where(temp_neg_mean<temp,tf.ones_like(temp),tf.zeros_like(temp)) * tf.where(temp_pos_mean>temp,tf.ones_like(temp),tf.zeros_like(temp)) 

temp1 = temp_between * temp
temp2 = (1-temp_between) * temp

all_of_data = sess.run([temp,
                        temp_pos,temp_pos_mean,
                        temp_neg,temp_neg_mean,temp1,temp2])

print(all_of_data[0])

print(all_of_data[1])
print(all_of_data[2])
print(all_of_data[3])

print(all_of_data[4])
print(all_of_data[5])
print(all_of_data[6])






[-0.9791961  1.3355689 -0.5717732  1.6240884  0.5671745]
[0. 1. 0. 1. 1.]
1.1756105
[1. 0. 1. 0. 0.]
-0.7754846
[-0.         0.        -0.5717732  0.         0.5671745]
[-0.9791961  1.3355689 -0.         1.6240884  0.       ]
